### ISSUE TITLE
How to Visualize results on KITTI/Flying chairs datasets?

### ISSUE THREAD

**Issue by sankhanrsss** [xingyul/flownet3d#11]
@xingyul 

I got your evaluation code , but how to visualize the flow in the paper you have shown. Kindly give some hints

**Comment by ymxlzgy** [comment]
@sankhanrsss use mayavi

**Comment by munib94** [comment]
@ymxlzgy can you help me with issue https://github.com/xingyul/flownet3d/issues/45?
