### ISSUE TITLE
Is the evaluation result related to the Graphics card?

### ISSUE THREAD

**Issue by hengwangzhao** [xingyul/flownet3d#12]
Thanks for your work!

With your processed data(11G) and the pre-trained model, I ran the code in two PCs.
Environments are the same: ubuntu 16.04, python3.5, TF1.9.0, Cuda 9.0

PC1: 1060(6g), i7 8700, 16g

PC2: 1080ti(11g), Xeon-E5, 32g

**Results of PC1**
---- EVALUATION ----
000/126
020/126
040/126
060/126
080/126
100/126
120/126
eval mean loss: 0.037443
eval mean EPE 3D: 0.188115
eval mean ACC 3D: 0.175726
eval mean ACC 3D 2: 0.487984

**Results of PC2**
---- EVALUATION ----
000/126
020/126
040/126
060/126
080/126
100/126
120/126
eval mean loss: 0.024307
eval mean EPE 3D: 0.147914
eval mean ACC 3D: 0.286565
eval mean ACC 3D 2: 0.616701

We can find that the results of PC2 are much better than those of PC1.
Everything is the same except for the computer hardware. Also, I have never trained yet, just use the provided pre-trained model.

What caused the difference in results? The graphics card? The memory?

**Comment by xingyul** [comment]
Could you check the Makefiles to see if everything is set correctly?
