### ISSUE TITLE
undefined symbol:_ZN10tensorflow8internal21CheckOpMessageBuilder9NewStringEv

### ISSUE THREAD

**Issue by anjingde** [xingyul/flownet3d#14]
I use 
python3.5 cuda9.2 tensorflow1.10.0  GCC  4.8.5

tensorflow.python.framework.errors_impl.NotFoundError: /disk2/wjn/flownet3d/tf_ops/sampling/tf_sampling_so.so: undefined symbol:_ZN10tensorflow8internal21CheckOpMessageBuilder9NewStringEv

I  try to  remove -D_GLIBCXX_USE_CXX11_ABI=0,  But it doesn't work.

**Comment by xingyul** [comment]
We used g++ 5.4.0. Could you try to upgrade gcc/g++ and try again?

**Comment by hehefan** [comment]
The problem may be caused by multiple tensorflow versions in the same machine.

**Comment by moizsajid** [comment]
In my case, I had to set ```-D_GLIBCXX_USE_CXX11_ABI=1``` in order to successfully run the ```Makefile```
