### ISSUE TITLE
Color features for KITTI scene flow dataset?

### ISSUE THREAD

**Issue by HimangiM** [xingyul/flownet3d#15]
Hi Xingyu,

I noticed that the preprocessed KITTI scene flow dataset that you had provided only contains the xyz coordinates for the pc1, pc2 and flow-gt. However, to run the evaluate.py, the model also needs the color features to run. Can you please also provide these features as part of the dataset?

Thanks

**Comment by amirstar** [comment]
Color features are 0 for KITTI dataset: 
https://github.com/xingyul/flownet3d/issues/23#issuecomment-534760773

**Comment by xingyul** [comment]
Please see 3d6c7cb.
