### ISSUE TITLE
KNN or Ball Point query in flow embedding layer?

### ISSUE THREAD

**Issue by HimangiM** [xingyul/flownet3d#16]
Hi

For the flow embedding layer, in the paper, the method of ball point query and radius have been mentioned. Then, why does this layer in the code has the parameter knn as True? 

Moreover, when I try to run the code with ball point query and radius = 5, it throws the error of CUDA_ERROR_ILLEGAL_ADDRESS. Can you advise on resolving this issue?

Thanks

**Comment by xingyul** [comment]
Thanks for asking. Please see https://github.com/xingyul/flownet3d/commit/b95cc8e7b7d1fffb1ca33dc6032c17dfd86b82f9.
