### ISSUE TITLE
Mean Loss Val: nan

### ISSUE THREAD

**Issue by Arjung27** [xingyul/flownet3d#19]
Hi Xingyul,

Thank you for providing your code here. I was trying to replicate the results from your paper and I am facing an issue doing that. When I run the code with the processed data you have provided I get my prediction scores as 'nan' (after 0.5 epoch only). As a result the loss value is 'nan' too. Please let me know what am I missing here? 

Looking forward to your reply.

**Comment by xingyul** [comment]
Thanks for bringing this up. I added one line to exclude this bad datapoint in 3a4b3b6.
