### ISSUE TITLE
a bug:undefined symbol: _ZN10tensorflow8internal21CheckOpMessageBuilder9NewStringEv

### ISSUE THREAD

**Issue by zhouxuting** [xingyul/flownet3d#2]
Hi, Xingyu, thank you for providing the code. I run your code and got a bug, I guess it might because of the configuration. 
My configuration is:
CUDA:9.0
Tensorflow-gpu1.9.0
gcc:4.8.5
Ubuntu:16.04
Is there any problem in my config ? and did you face similar problem?

Yours,
Xuting

**Comment by xingyul** [comment]
Thanks for this note. It seems that the problem is during the g++ compilation.
My configuration uses g++ (and gcc) 5.4.0. Could you update it to 5.4.0 and see if it works?

**Comment by zhouxuting** [comment]
Thank you for your advice. I tried gcc 5.4.0, but i still met the same problem. I use "readelf -p .comment tf_sampling_so.so  " to check the gcc version and found  [     0]  GCC: (GNU) 5.4.0   [    11]  GCC: (GNU) 4.8.5 20150623 (Red Hat 4.8.5-4). it seems like two gcc versons. Is this the problem from? or do you have some other suggestion to solve this problem?

Best regards,
Xuting

**Comment by zhouxuting** [comment]
Thank you a lot. I have solved this problem through updating gcc to 5.4 version and delete -O2 -D_GLIBCXX_USE_CXX11_ABI=0 in ../tf_ops/../Makefile . 

Best regards,
Xuting
