### ISSUE TITLE
Is the KITTI result in paper evaluated with or without colour?

### ISSUE THREAD

**Issue by Ryan-Zirui-Wang** [xingyul/flownet3d#23]
Hi xingyul,

Thanks for your code and all preprocessing dataset. Can I ask is your KITTI result in your paper is evaluated with XYZ feature only? or is it evaluated use 6 channels (XYZ-RGB) but with rgb filled with some constants? or is it evaluated with full XYZ-RGB features?

Best,
Zirui

**Comment by xingyul** [comment]
It is evaluated without color, i.e. 6 channels (XYZ-RGB) with RGB filled with zeros.
