### ISSUE TITLE
Using the first 2048 points of the point clouds stored in the cache?

### ISSUE THREAD

**Issue by dyh127** [xingyul/flownet3d#26]
In the function __getitem__ in flying_things_dataset.py, the point clouds, stored in the cache,  are not randomly sampled with 2048 points and are returned with 8192 points. In this case, in the function get_batch in train.py, only first 2048 points of these point clouds will be used.

So I guess, there might exist an indentation problem between line47 and line65 in flying_things_dataset.py.

**Comment by xingyul** [comment]
Thanks a lot for pointing that out! Problem fixed in fbc174f.
