### ISSUE TITLE
How do you evaluate your method on KITTI？

### ISSUE THREAD

**Issue by sulashi** [xingyul/flownet3d#29]
I found that your evaluation code did not include the part about "On large KITTI scenes,
we split the scene into multiple chunks." in your paper.  And the points are always the 2048 points first. 

If you use the method of your paper for evaluation on KITTI, how can you make sure that you get all points for evaluation in frame one?

**Comment by xingyul** [comment]
Hi, for KITTI experiments, please see 3d6c7cb. We released an implementation without splitting the scenes into chunks. You can also try to split the scenes into chunks with some more engineering efforts.
