### ISSUE TITLE
how to test with pointcloud dataset with only xyz input

### ISSUE THREAD

**Issue by zhouxuting** [xingyul/flownet3d#3]
Hi, thank you for sharing your code. I generate my own dataset with points1 xyz and points2 xyz and gt flow, but without color1 and color2.  I tried to use my own dataset to test trained model, but there are always some format errors. Do you have the code which is compatible with my dataset?

Thank you !

Best regards,
Xuting

**Comment by xingyul** [comment]
Hi, we have provided sample dataset reading code in ``flying_things_dataset.py``. If your points don't have rgb values, you can simply set color1 and color2 to be all zeros when you are generating your dataset.

**Comment by anjingde** [comment]
Hi,thank you,my points don‘t have rgb values. When I test,    I set mask1 to be all ones .is it okay?

**Comment by xingyul** [comment]
mask1 is for loss masking. It won't affect testing. But if your points don't have rgb values during training, it would be a good idea to set all rgb values to zero.
