### ISSUE TITLE
huge prediction value

### ISSUE THREAD

**Issue by liyang1991c** [xingyul/flownet3d#38]
Hi, I download the pretrained model and the processed data.
Then I evaluate the model using the given scripts.  
I keep getting very huge loss like this:

> loss value 
>  1019623.6
> pred_value 
>  [[[-1183.0692   -451.19238  -942.2431 ]
>   [-1617.0183   -613.1068  -1288.0482 ]
>   [-1646.4847   -628.52234 -1312.6896 ]
>   ...
>   [-1316.52     -497.82248 -1044.1621 ]
>   [ -975.26605  -370.09656  -777.7711 ]
>   [-1316.516    -497.82562 -1044.1562 ]]]
> 
> loss value 
>  5635.0854
> pred_value 
>  [[[-181.02733     78.97927     54.753517 ]
>   [ -60.915703    37.60071      5.6472397]
>   [-143.16997     68.90349     30.370804 ]
>   ...
>   [-141.26614     68.30685     29.489553 ]
>   [-143.37962     68.98323     30.424229 ]
>   [ -94.74317     50.511147    22.388628 ]]]

Do you have any idea about this? Thx.

**Comment by xingyul** [comment]
It's likely that the CUDA Op is not compiled correctly. Please check the `arch` flag in Makefiles.

**Comment by liyang1991c** [comment]
@xingyul Thanks.  Btw, Do you know how to check the "arch" of my CUDA?

**Comment by liyang1991c** [comment]
Thanks. It works.
