### ISSUE TITLE
Using only XYZ values

### ISSUE THREAD

**Issue by Shubhendu-Jena** [xingyul/flownet3d#39]
Hi, thanks a lot for the previous reply. Just another doubt, in the function sample_and_group, if the flag use_xyz is set to true, we have : new_points = tf.concat([grouped_xyz, grouped_points], axis=-1) # (batch_size, npoint, nample, 3+channel). To use XYZ values only, instead of setting (R,G,B) = (0,0,0), I was doing new_points = grouped_xyz which gives me significantly different results. I can't figure out why this creates that much of a difference as I was grouping X,Y,Z coordinates without the concatenated (R,G,B) = (0,0,0) values. Can you please help me with this?

**Comment by xingyul** [comment]
Note `*_points` actually denotes the features, either the RGB values or the learned features from the previous layer. The variable name is a little confusing (and sorry about that). So you can only do `new_points = grouped_xyz` for the first layer. If you do that for the second layer and beyond, the features learned for the that layer is not passed to subsequent layers, so it will fail.

**Comment by Shubhendu-Jena** [comment]
Thank you!
