### ISSUE TITLE
About visualization and kitti dataset

### ISSUE THREAD

**Issue by zmlshiwo** [xingyul/flownet3d#4]
Hi,
Excellent work! I have trained the model and obtained close results to the paper on FlyingThings3D dataset. I have some problems. 1). How to visualize the scene flow like your paper? 2).  When will the training and test on the KITTI dataset be released? And, can you provide the pre-trained model? Thank you very much!
Best,
Zhai

**Comment by ymxlzgy** [comment]
Hi，Dr.Zhai，I just saw your issue 24 minutes ago，I want to ask that what study you are interested in，and I want to use scene flow to study 3D tracking and LiDAR SLAM. I have not run this code by now，so I want to know the real-time performance of this method，thanks.

**Comment by ymxlzgy** [comment]
> Hi,
> Excellent work! I have trained the model and obtained close results to the paper on FlyingThings3D dataset. I have some problems. 1). How to visualize the scene flow like your paper? 2). When will the training and test on the KITTI dataset be released? And, can you provide the pre-trained model? Thank you very much!
> Best,
> Zhai
Hi，Dr.Zhai，I just saw your issue 24 minutes ago，I want to ask that what study you are interested in，and I want to use scene flow to study 3D tracking and LiDAR SLAM. I have not run this code by now，so I want to know the real-time performance of this method，thanks.

**Comment by ymxlzgy** [comment]
> Hi,
> Excellent work! I have trained the model and obtained close results to the paper on FlyingThings3D dataset. I have some problems. 1). How to visualize the scene flow like your paper? 2). When will the training and test on the KITTI dataset be released? And, can you provide the pre-trained model? Thank you very much!
> Best,
> Zhai

Hi，Dr.Zhai，I just saw your issue 24 minutes ago，I want to ask that what study you are interested in，and I want to use scene flow to study 3D tracking and LiDAR SLAM. I have not run this code by now，so I want to know the real-time performance of this method，thanks.

**Comment by zmlshiwo** [comment]
@ymxlzgy Hi, I have not tested the time. But I think the speed is fast .

**Comment by Ryan-Zirui-Wang** [comment]
Appendix G describes running time.

**Comment by chowkamlee81** [comment]
Whether any update to release code in KITTI dataset?

**Comment by xingyul** [comment]
KITTI dataset has been released.
