### ISSUE TITLE
Evaluation for occluded points

### ISSUE THREAD

**Issue by hurjunhwa** [xingyul/flownet3d#54]
Hi, thanks for the great work!

I have a short question for the evaluation.
Do you evaluate the scene flow for all 3D points? or only non-occluded points?

It seems like it only evaluates the scene flow for non-occluded points by using the **mask**:

https://github.com/xingyul/flownet3d/blob/ca2a2cb8e1e747949111fc4aa9d3bc010cc0e09b/evaluate.py#L105-L121

It will be appreciated if you can clarify this :)

**Comment by xingyul** [comment]
For the EPE metric, I believe we evaluated it on all points during testing. During training, however, we only train the points that are not occluded. In order to evaluate it on all points, you probably need to slightly change the evaluation code.
